#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys
import argparse
import traceback

# -----------------------------------------------------------------------------

parser = argparse.ArgumentParser(
    prog='meld',
    description='Process some integers.'
    parents=[],
    conflict_handler='resolve'
)

# -----------------------------------------------------------------------------

def main():
    try:
    except:
        print("main: execution failed ...")
        print("-" * 60)
        traceback.print_exc(file=sys.stderr)
        print("-" * 60)
    else:
        # return with success code
        return 0
    finally:
        pass

# -----------------------------------------------------------------------------

if __name__ == '__main__':
    sys.exit(main(*sys.argv))

# -----------------------------------------------------------------------------
